#!/bin/bash
sudo apt update
sudo apt upgrade
sudo apt install apache2 -y
sudo apt install libapache2-mod-wsgi-py3
sudo apt install python3 python3-venv python3-pip
sudo sed -i '/<\/VirtualHost>/ i Alias /static /home/pi/pidjango/static\n<Directory /home/pi/pidjango/static>\nRequire all granted\n</Directory>\n\n<Directory /home/pi/pidjango/pidjango>\n<Files wsgi.py>\nRequire all granted\n</Files>\n</Directory>\n\nWSGIDaemonProcess django python-path=/home/pi/pidjango python-home=/home/pi/pidjango/djenv\nWSGIProcessGroup django\nWSGIScriptAlias / /home/pi/pidjango/pidjango/wsgi.py' /etc/apache2/sites-enabled/000-default.conf
sudo systemctl restart apache2
mkdir -p /home/pi/pidjango/static
cd /home/pi/pidjango
python3 -m venv djenv
source djenv/bin/activate
pip3 install django
pip3 install Adafruit_DHT
django-admin startproject pidjango
cd pidjango/pidjango
sudo sed -i "s/raspberrypi/$1/g" /etc/hosts
sudo sed -i "s/raspberrypi/$1/g" /etc/hostname
echo 'setup complete rebooting...'
sudo reboot
